target_phrases = [  # List of target phrases here
    "born in",
    "getting divorced",
    "getting engaged",
    "getting married",
    "going down to",
    "got divorced",
    "got engaged",
    "got married",
    "job interview",
    "just visited",
    "just visiting",
    "live in",
    "living in",
    "moved to",
    "my address",
    "my aunty",
    "my birthday",
    "my brother",
    "my children",
    "my child",
    "my daughter",
    "my email",
    "my family",
    "my father",
    "my grandchildren",
    "my grandchild",
    "my granddaughter",
    "my grandson",
    "my home address",
    "my hometown",
    "my home",
    "my house",
    "my husband",
    "my job",
    "my kids",
    "my kid",
    "my little ones",
    "my little one",
    "my mother",
    "my nephew",
    "my niece",
    "my parents",
    "my partner",
    "my phone number",
    "my profession",
    "my school",
    "my siblings",
    "my sibling",
    "my significant other",
    "my sister",
    "my son",
    "my SO",
    "my spouse",
    "my stepfather",
    "my stepmother",
    "my uncle",
    "my university",
    "my wife",
    "new job",
    "our children",
    "our daughter",
    "our kid",
    "our son",
    "to school at",
    "to university at",
    "went down to",
    "went up to",
    "where I grew up",
    "where I grew up",
    "where I live",
    "where I live",
    "where I work",
    "where I work",
    "work at",
]

target_phrase_sections = [
    (
        "Racism/Hate Speech",
        [  # List of target phrases for section 1
            "chinks",
            "chink",
            "faggots",
            "faggot",
            "fags",
            "fag",
            "femoids",
            "femoid",
            "foid",
            "Gibsmedat",
            "gibs",
            "gooks",
            "Goy",
            "groomers",
            "groomer",
            "jewish",
            "jews",
            "jew",
            "kikes",
            "kike",
            "moggers",
            "mogger",
            "mongrels",
            "mongrel",
            "moslems",
            "moslem",
            "mudshits",
            "mudshit",
            "mudslimes",
            "mudslime",
            "mulattos",
            "mulatto",
            "muzzies",
            "negroids",
            "negroid",
            "niggers",
            "nigger",
            "pakis",
            "paki",
            "rapefugees",
            "sand niggers",
            "sand nigger",
            "sandnigs",
            "sandnig",
            "shit skin",
            "shitskins",
            "shitskin",
            "soyboys",
            "soyboy",
            "spics",
            "towel heads",
            "towel head",
            "towelheads",
            "towelhead",
            "trannys",
            "tranny",
            "zogbots",
            "zogbot",
            "(((",
        ],
    ),
    (
        "Indicators - White Identity Motivated Extremism",
        [  # List of target phrases for section 2
            "6MWNE",
            "14 words",
            "14-88",
            "14/88",
            "88/HH",
            "1488",
            "1788",
            "accelerate",
            "Accelerationism",
            "Accelerationist",
            "accelerationist",
            "anti-Zionist",
            "Aryan",
            "Ashkenazis",
            "blood and soil",
            "brevik",
            "Clown World",
            "coal burner",
            "cultural jihad",
            "cultural marxism",
            "cultural marxists",
            "day of the rope",
            "demographic decline",
            "demographic replacement",
            "deus vault",
            "did nothing wrong",
            "ethnostate",
            "ethno-nationalist",
            "FGRN",
            "goyim",
            "GTKRWN",
            "hitler",
            "Holocauster",
            "Holohoax",
            "IOTBW",
            "iron pilled",
            "iron pill",
            "its okay to be white",
            "it's ok to be white",
            "it's okay to be white",
            "James Mason",
            "jewish question",
            "kebab removalist",
            "kek",
            "Khazarian",
            "national socialism",
            "national socialist",
            "pro western values",
            "pro-western values",
            "pro-white activism",
            "race traitors",
            "race traitors",
            "race traitor",
            "race traitor",
            "RACE WAR NOW",
            "Racial Holy War",
            "RaHoWa",
            "remove kebabs",
            "remove kebab",
            "sieg heil",
            "siege pilled",
            "siege pill",
            "Tarrant",
            "terrorgram",
            "the great replacement",
            "tradthot",
            "tradwife",
            "waffen",
            "western culture",
            "white genocide",
            "white is right",
            "white lives matter",
            "white nationalist",
            "white power",
            "white pride",
            "white race",
            "ZOG",
            "zyklon B",
            "Z.O.G.",
            "#WhiteLivesMatter",
            "//",
            "⚡",
            "🤡🌎",
        ],
    ),
    (
        "Indicators - Faith Motivated Extremism",
        [  # List of target phrases for section 3
            "al-Emarah",
            "Al-hayat",
            "al-Tawaghit",
            "apostate",
            "A’maq Agency",
            "Baqiya wa tatamaddad",
            "Dabiq",
            "holy war",
            "in the shadow of the caliphate",
            "Istishaadi",
            "Jihad",
            "lions of the Islamic State",
            "may God accept him",
            "Rafidha",
            "Rawafidh",
            "Remaining and Expanding",
            "shariyah",
            "soldiers of the caliphate",
            "the apostates",
            "the crusader coalition",
            "The encyclopedia of Jihad",
            "The Mujahidin Handbook",
            "the prophetic methodology",
            "the prophetic methodology",
            "tyrants",
            "أسود الدولة الإسلامية",
            "استيشادي",
            "التحالف الصليبي",
            "التواغيت",
            "الخلافة الإسلاميةروافيض",
            "الدولة الإسلامية",
            "الشريعة",
            "الطغاة",
            "المتبقية والتوسع",
            "المرتدين",
            "المنهج النبوي",
            "المنهجية المؤيدة للفيتيك",
            "باقية من تاتاداد",
            "تقبل الله الله",
            "جنود الخلافة",
            "جهاد",
            "جهاد",
            "دليل المجاهد",
            "رفيدة",
            "في ظل الخلافة",
            "مرتد",
            "موسوعة الجهاد",
        ],
    ),
    (
        "Indicators - Conspiratorial Ideation",
        [  # List of target phrases for section 4
            "adrenochrome",
            "agenda 21",
            "agenda 2030",
            "cabal",
            "chemtrails",
            "crimes against humanity",
            "deep state",
            "false flag",
            "freemasons",
            "freemason",
            "geotus",
            "globalists",
            "globalist",
            "great awakening",
            "great reset",
            "illuminati",
            "Microchipped",
            "microchips",
            "new world order",
            "nuremberg",
            "nuremburg",
            "pizzagate",
            "rothschilds",
            "sheeple",
            "the storm",
            "the storm",
            "world economic forum",
            "WWG1WGA",
        ],
    ),
    (
        "Indicators - Sovereign Citizen",
        [  # List of target phrases for section 5
            "14th amendment",
            "admiralty law",
            "affidavit of truth",
            "Artifical Construct",
            "Artificial Construct",
            "Birth Certificate Bond",
            "Commercial Redemption",
            "common law",
            "Constitutional Sheriff",
            "Corpus Juris",
            "flesh and blood",
            "free man",
            "free woman",
            "Freeman Passport",
            "Freemen Standby Act",
            "in admiralty",
            "In the Private",
            "Informed Consent",
            "Lawful Dissent",
            "legal fiction",
            "letters of marque",
            "living man",
            "living soul",
            "living woman",
            "Magna Carta",
            "man on the land",
            "Maritime Law",
            "Maxim of Law",
            "Natural Law",
            "Nontaxpayer",
            "Non-Domiciled Resident",
            "non-resident alien",
            "non-resident alien",
            "notice of understanding and intent",
            "Policy Officer",
            "Postmaster",
            "Quantam Grammar",
            "Quantum Grammar",
            "Settlor",
            "sovereign citizen",
            "sovreign citizen",
            "Strawman",
            "strawman",
            "Sui Juris",
            "Uniform Commercial Code",
        ],
    ),
    (
        "Indicators - Involuntary Celibate",
        [  # List of target phrases for section 6
            "alpha male",
            "beta male",
            "black pilled",
            "blackpilled",
            "braincels",
            "chad",
            "cucks",
            "dog pilled",
            "dog pill",
            "Elliot Rodger",
            "fakecel",
            "femoid",
            "foid",
            "gamma male",
            "genetically inferior",
            "going ER",
            "have a little fun bEfoRe you go",
            "incels",
            "incel",
            "incel",
            "Manosphere",
            "Men going their own way",
            "Mens Rights Activists",
            "MGTOW",
            "omega male",
            "ragefuel",
            "rape fuel",
            "red pilled",
            "red pill",
            "red-pilled",
            "roasties",
            "ropefuel",
            "Sexual Market Value",
            "SMV",
            "Supreme Gentleman",
            "truecel",
        ],
    ),
    (
        "Indicators - Dehumanizing Rhetoric",
        [  # List of target phrases for section 7
            "demonic",
            "demon",
            "leeches",
            "leech",
            "maggots",
            "maggot",
            "mongrels",
            "mongrel",
            "parasites",
            "parasites",
            "parasite",
            "scum",
            "soulless",
            "sub-human",
            "vermin",
        ],
    ),
]

target_phrase_list1 = [
    "3d printed",
    "3d print",
    "3d-printed",
    "3d-print",
    "acquire",
    "acquiring",
    "borrow",
    "buying",
    "buy",
    "certified",
    "getting",
    "get",
    "ghost gun",
    "got",
    "have",
    "license",
    "my",
    "need",
    "obtaining",
    "obtain",
    "owning",
    "own",
    "procure",
    "procuring",
    "steal a",
    "stolen",
    "take",
    "want agoing to",
    "want to",
    "wanting",
    "with"
]

target_phrase_list2 = [
    "9 mm",
    "9mm",
    "12 gauge",
    "12gauge",
    "12ga",
    "22",
    "50 cal",
    "50cal",
    "85",
    "590",
    "629",
    "870",
    "AK-47",
    "ammonium nitrate",
    "ammo",
    "ammunition",
    "ar15",
    "armor-piercing",
    "AR",
    "ar-15",
    "AR-556",
    "ball bearings",
    "barrel",
    "benelli",
    "beretta",
    "bipod",
    "bird shot",
    "birdshot",
    "blasting cap",
    "body armour",
    "bolt-action",
    "bolt-action",
    "boom stick",
    "buck shot",
    "buckshot",
    "bushmaster",
    "caliber",
    "chamber a round",
    "Colt",
    "compensator",
    "compound bow",
    "crossbow",
    "det cord",
    "detcord",
    "detonater",
    "detornaters",
    "doublebarreled",
    "doublebarrel",
    "double-barreled",
    "double-barrel",
    "duck shooting",
    "explosives",
    "fertilizer",
    "fire bomb",
    "firearms training ",
    "firearms",
    "firearm",
    "firebomb",
    "firing pin",
    "fully automatic",
    "G19",
    "gauge",
    "geissele",
    "glock",
    "grenades",
    "grenade",
    "gun range",
    "gun",
    "hollow points",
    "hollow point",
    "hunting",
    "IED",
    "improvised explosive device",
    "kel-tec",
    "kevlar",
    "knife",
    "KSG",
    "landmine",
    "LE6920",
    "lever action",
    "lever-action",
    "M4",
    "M16",
    "M1911",
    "machine gun",
    "magazine",
    "molotov",
    "muzzle",
    "M&P15",
    "M&P",
    "nitrate",
    "nitroglycerin",
    "optics",
    "pipe bomb",
    "pipebombs",
    "pipebomb",
    "pipe-bombs",
    "pipe-bomb",
    "pistol",
    "propellant",
    "pump-action",
    "remington",
    "revolver",
    "rifle club",
    "rifle",
    "ruger",
    "sawn off",
    "sawnoff",
    "sawn-off",
    "scope",
    "semiautomatic",
    "semi-automatic",
    "semtex",
    "shooting practice",
    "shooting range",
    "shotgun",
    "sig",
    "silencer",
    "SMG",
    "Smith & Wesson",
    "springfield",
    "stabproof vest",
    "stab-proof vest",
    "stock",
    "suppressor",
    "S&W",
    "tannerite",
    "target practice",
    "target shooting",
    "taurus",
    "thermalite",
    "thermite",
    "TNT",
    "Winchester",
    ".22",
    ".30",
    ".45",
    ".50",
    ".85"
]

target_phrase_list3 = [
    "and attack",
    "and execute",
    "and exterminate",
    "and gut",
    "and hang",
    "and kill",
    "and kill",
    "and lynch",
    "and murder",
    "and rape",
    "and shoot",
    "and slaughter",
    "and stab",
    "attack her",
    "attack him",
    "attack them",
    "be executed",
    "be exterminated",
    "be exterminated",
    "be hanged",
    "be hung",
    "be killed",
    "be murdered",
    "be raped",
    "be shot",
    "be slaughtered",
    "be stabbed",
    "be strangled",
    "beheaded",
    "behead",
    "by the neck",
    "by the throat",
    "cable ties",
    "cable tie",
    "cabled tied",
    "curb stomped",
    "curb stomp",
    "decapitated",
    "decapitate",
    "double tap",
    "execute them",
    "exterminate her",
    "exterminate him",
    "exterminate them",
    "fucking attack",
    "fucking execute",
    "fucking exterminate",
    "fucking head",
    "fucking kill",
    "fucking murder",
    "fucking neck",
    "fucking shoot",
    "fucking skull",
    "fucking slaughter",
    "fucking stab",
    "fucking throat",
    "get executed",
    "get killed",
    "get murdered",
    "get raped",
    "get shot",
    "get stabbed",
    "gonna execute",
    "gonna kill",
    "gonna murder",
    "gonna rape",
    "gonna shoot ",
    "gonna stab ",
    "gonnahang",
    "gut her",
    "gut him",
    "gut them",
    "gut you",
    "hang them",
    "her to death",
    "him to death",
    "hog tied",
    "hog tie",
    "hogtied",
    "hogtie",
    "in the face",
    "in the head",
    "in the neck",
    "in the throat",
    "lynch her",
    "lynch him",
    "lynch them",
    "lynched",
    "my fist",
    "punch her",
    "punch him",
    "punch you",
    "rag dolled",
    "rag doll",
    "ragdolled",
    "ragdoll",
    "should attack",
    "should execute",
    "should exterminate",
    "should hang",
    "should kill",
    "should murder",
    "should rape",
    "should shoot",
    "should slaughter",
    "should stab",
    "slaughter her",
    "slaughter him",
    "slaughter them",
    "strangle her",
    "strangle him",
    "strangle them",
    "strangle you",
    "string her up",
    "string him up",
    "string them up",
    "strung up",
    "take a hostage",
    "take hostages",
    "tar and feather",
    "them to death",
    "to attack",
    "to die",
    "to execute",
    "to exterminate",
    "to gut",
    "to kill",
    "to k*ll",
    "to lynch",
    "to murder",
    "to rape",
    "to sh00t",
    "to shoot",
    "to slaughter",
    "to stab",
    "will execute",
    "will kill",
    "will k*ll",
    "will murder",
    "will rape",
    "will shoot",
    "will stab",
    "will strangle",
    "you to death"
]
